repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
-   repo: local
    hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      types: [python]
      exclude: (?x)^(django_admin/.* |etl/queries/.*)$
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args: ["--profile", "black"]